BOT_NAME = "parser"

SPIDERS_MODULE = "parser.spiders"

SPIDER_MODULES = [SPIDERS_MODULE]
NEWSPIDER_MODULE = SPIDERS_MODULE

ADDONS = {}

ROBOTSTXT_OBEY = False

CONCURRENT_REQUESTS_PER_DOMAIN = 1
DOWNLOAD_DELAY = 1

ITEM_PIPELINES = {
    "parser.pipelines.DatabasePipeline": 300,
}

FEED_EXPORT_ENCODING = "utf-8"
